### ISSUE TITLE
Fails to compile with the NAG compiler

### ISSUE THREAD

**Issue by certik** [lanl/SNAP#15]
```
nagfor  -c setup.f90
NAG Fortran Compiler Release 7.0(Yurakucho) Build 7026
Error: setup.f90, line 860: Missing comma in format specification
       detected at 'Group         Total         Absorption      '@'Scattering'
Error: setup.f90, line 945: Missing comma in format specification
       detected at 'Column-order loops:'@' Mats (fastest ), Moments, Groups, Groups (slowest)'
[NAG Fortran Compiler pass 1 error termination, 2 errors]
```

**Comment by zerr** [comment]
I believe the // operator doesn't work in a `FORMAT` statement, but I think it should adhere to standard where I use it to combine two strings into one `CHARACTER` variable, only breaking them up for style formatting.

Closing this, because I didn't see any other issues or changes for those instances in the PRs. Please re-open if still running into issues with NAG.

**Comment by certik** [comment]
Thank you @zerr. It seems to be fixed now. If there is anything else, I'll open new issues / PRs. Thanks!
